name: Provision Infrastructure
# Run this workflow every time a change is pushed to main
on:
  push:
    branches:
      - main
    paths:
      - "infra/**"
jobs:
  provision:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
    name: Provision Infrastructure
    # Set the type of machine to run on
    runs-on: ubuntu-latest
    steps:
    # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
    # Install Pulumi and add it to our PATH
      - name: Install Pulumi
        run: |
          curl -fsSL https://get.pulumi.com | sh
          echo "/home/runner/.pulumi/bin" >> $GITHUB_PATH
    # Install dependencies and  deploys resources by running "pulumi up" command
      - name: Deploy Infra
        run: |
          sudo pip install pipenv
          pipenv lock
          pipenv sync
          pipenv run npm install
          pipenv run pulumi up --yes --stack Aleksandrov/infra/dev --suppress-outputs
        env:
        # Supplying environment variables to interact with AWS Cloud provider
        # and allow Pulumi CLI to communicate with Pulumi Service  
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_REGION: ${{ env.AWS_REGION }}
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          #PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}
